version: 1
settings:
  on_error: continue
  cleanup_source: false
  cleanup_output_after_print: true
input:
  path: input
  pattern: '*.pdf'
outputs:
  packing_sheet:
    pages: 1--1
    output_dir: output
    filename_suffix: _1
    print:
      enabled: true
      merge: true
      targets:
        BrotherLaser:
          printer: Brother HL-L2420DW Printer
          weight: 1
          copies: 1
  label:
    pages: last
    output_dir: output
    filename_suffix: _2
    transforms:
    - rotate: 90
    - crop:
        lower_left:
        - 90mm
        - 33mm
        upper_right:
        - 190mm
        - 183mm
    - size:
        width: 100mm
        height: 150mm
        fit: stretch
    print:
      enabled: true
      merge: true
      targets:
        default:
          printer: PL80E
          weight: 1
          copies: 1
