version: 1
settings:
  on_error: continue
  cleanup_source: false
  cleanup_output_after_print: false
input:
  path: input
  pattern: Lecture*.pdf
  sort: name_asc
outputs:
  default:
    pages: '1'
    output_dir: output
    debug: true
    transforms:
    - split:
        regions:
        - lower_left:
          - 45mm
          - 150mm
          upper_right:
          - 170mm
          - 240mm
        - lower_left:
          - 45mm
          - 36mm
          upper_right:
          - 170mm
          - 126mm
    - combine:
        page_size:
        - 8.5in
        - 11in
        pages_per_output: 2
        layout:
        - page: 0
          position:
          - 1in
          - 5.5in
          scale: 1.3
        - page: 0
          position:
          - '1'
          - '1'
          scale: 1.3
